version: '3'
services:
  postgres:
    image: 'bitnami/postgresql:9.6'
    container_name: gitpm-internal-postgres
    volumes:
      - gitpm-postgres:/bitnami
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_DATABASE=${DB_NAME}
    restart: always
  gitpm-app:
    build: .
    container_name: gitpm-internal-gitpm
    env_file: .env
    volumes:
      - "./gitpm-app:/go/src/github.com/gitpmio/gitpm/gitpm-app"
    ports:
      - "8080:8080"
volumes:
  gitpm-postgres:
  gitpm-rabbit:
